//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class budjet
    {
        public decimal budjet1 { get; set; }
        public Nullable<decimal> proc_cost { get; set; }
        public Nullable<decimal> prem_proc { get; set; }
        public int id { get; set; }
    }
}
