//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class credit
    {
        public credit()
        {
            this.Repayments = new HashSet<Repayment>();
        }
    
        public int id { get; set; }
        public string bank { get; set; }
        public Nullable<System.DateTime> date_of_issue { get; set; }
        public Nullable<float> fine { get; set; }
        public Nullable<float> percent { get; set; }
        public Nullable<float> sum { get; set; }
        public Nullable<int> year { get; set; }
        public Nullable<float> redeemed { get; set; }
    
        public virtual ICollection<Repayment> Repayments { get; set; }
    }
}
