//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class month
    {
        public month()
        {
            this.salaries = new HashSet<salary>();
        }
    
        public byte id { get; set; }
        public string month1 { get; set; }
    
        public virtual ICollection<salary> salaries { get; set; }
    }
}
