//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class raw
    {
        public raw()
        {
            this.buyings = new HashSet<buying>();
            this.consists = new HashSet<consist>();
        }
    
        public int id { get; set; }
        public string raw1 { get; set; }
        public Nullable<int> unit { get; set; }
        public Nullable<decimal> count { get; set; }
        public Nullable<decimal> cost { get; set; }
        public Nullable<decimal> sum { get; set; }
    
        public virtual ICollection<buying> buyings { get; set; }
        public virtual ICollection<consist> consists { get; set; }
        public virtual unit unit1 { get; set; }
    }
}
