//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Repayment
    {
        public int id { get; set; }
        public Nullable<int> bank { get; set; }
        public Nullable<System.DateTime> payment_date { get; set; }
        public Nullable<float> sum_All { get; set; }
        public Nullable<float> payment_sum { get; set; }
        public Nullable<float> percents { get; set; }
        public Nullable<float> fine { get; set; }
    
        public virtual credit credit { get; set; }
    }
}
