//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class unit
    {
        public unit()
        {
            this.products = new HashSet<product>();
            this.raws = new HashSet<raw>();
        }
    
        public int id { get; set; }
        public string unit1 { get; set; }
    
        public virtual ICollection<product> products { get; set; }
        public virtual ICollection<raw> raws { get; set; }
    }
}
