//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class worker
    {
        public worker()
        {
            this.buyings = new HashSet<buying>();
            this.makings = new HashSet<making>();
            this.sellings = new HashSet<selling>();
            this.salaries = new HashSet<salary>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public Nullable<int> post { get; set; }
        public string address { get; set; }
        public string phone { get; set; }
        public Nullable<decimal> salary { get; set; }
        public string login { get; set; }
        public string password { get; set; }
    
        public virtual ICollection<buying> buyings { get; set; }
        public virtual ICollection<making> makings { get; set; }
        public virtual post post1 { get; set; }
        public virtual ICollection<selling> sellings { get; set; }
        public virtual ICollection<salary> salaries { get; set; }
    }
}
